package zioapp.error

import java.io.IOException

import capture.Capture
import capture.Capture.Constructors

trait WeatherErr[+A] {
  def weatherClient(error: IOException): A

  def unknownCity(city: String): A
}

//this probably should be generated by some macro
object WeatherErr extends Constructors[WeatherErr] {
  def weatherClient(error: IOException) = Capture[WeatherErr](_.weatherClient(error))

  def unknownCity(city: String) = Capture[WeatherErr](_.unknownCity(city))
}
